# Generated by Django 5.2.1 on 2025-06-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Place')),
                ('forecast_today', models.JSONField(blank=True, verbose_name='Forecast Today')),
                ('forecast_tomorrow', models.JSONField(blank=True, verbose_name='Forecast Tomorrow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
